module.exports = [
  { from: "/pirts-rituals.php", to: "/pirts-rituali" },
  { from: "/lauku-spa.php", to: "/pirts-rituali/meitenu-spa-vakars" },
  { from: "/naktsmitnes.php", to: "/viesu-maja" },
  { from: "/aktivaatputa.php", to: "/aktiva-atputa" },
  { from: "/cenas.php", to: "/pirts-rituali" },
  { from: "/atsauksmes.php", to: "/atsauksmes" },
  { from: "/kontakti.php", to: "/kontakti" },
  { from: "/ru/pirts-rituals.php", to: "/ru/pirts-rituali" },
  { from: "/ru/lauku-spa.php", to: "/ru/pirts-rituali/meitenu-spa-vakars" },
  { from: "/ru/naktsmitnes.php", to: "/ru/viesu-maja" },
  { from: "/ru/aktivaatputa.php", to: "/ru/aktiva-atputa" },
  { from: "/ru/cenas.php", to: "/ru/pirts-rituali" },
  { from: "/ru/atsauksmes.php", to: "/ru/atsauksmes" },
  { from: "/ru/kontakti.php", to: "/ru/kontakti" },
  { from: "/en/pirts-rituals.php", to: "/en/pirts-rituali" },
  { from: "/en/lauku-spa.php", to: "en/pirts-rituali/meitenu-spa-vakars" },
  { from: "/en/naktsmitnes.php", to: "/en/viesu-maja" },
  { from: "/en/aktivaatputa.php", to: "/en/aktiva-atputa" },
  { from: "/en/cenas.php", to: "/en/pirts-rituali" },
  { from: "/en/atsauksmes.php", to: "/en/atsauksmes" },
  { from: "/en/kontakti.php", to: "/en/kontakti" },
  { from: "/viesu-maja/[slug]", to: "/viesu-maja"},
  { from: "/pirts-rituali/[slug]", to: "/pirts-rituali"},
  { from: "/galerijas/[slug]", to: "/galerijas/viesu-majas-ire"},
];
